### ISSUE TITLE
Being able to "mass"-parent and unparent multiple selected cubes

### ISSUE THREAD

**Issue by kashgummaraju** [Dumb-Code/DumbCode-Studio#104]
- Ideally this feature/function would be used to parent multiple selected cubes to the same parent or simply unparent them from their respective parent(s)
- Right now the only solution to change the parent of multiple cubes is to drag them up and down the list, one by one.

**Comment by BrownBoiiWonder** [comment]
- Maybe some kind of parent/unparent command similar to vertex snapping could be done to parent and unparent without using the cube list.
- Selecting the command and picking the "Parent" option would allow you to then select the target cube and then you would select the cube to parent it to. "Unparent" would be similar in that it would automatically unparent the cube from its immediate Parent cube, and each time you press "Unparent", it would unparent from every parent cube up the chain.
- And pressing ctrl would allow you to select multiple cubes for the initial child cube selection

**Comment by Wyn-Price** [comment]
what about a command `parent` and `unparent`

**Comment by NeusFear** [comment]
> what about a command `parent` and `unparent`

I think that would be a good solution

**Comment by NeusFear** [comment]
tracked in #193 apparently
