### ISSUE TITLE
Texturer should have a way to split layers into texture groups

### ISSUE THREAD

**Issue by NeusFear** [Dumb-Code/DumbCode-Studio#108]
An example of this is with the male and female textures on the trex model, there should be an easy way to switch between these skins without having both skin's layers all visible at the same time on the texture tab

**Comment by Wyn-Price** [comment]
Needed for the branch:
- [ ] `Texture Layer` option shouldn't show when theres no texture layers
- [ ] UI for editing texture layer should be moved from a modal to be in the texture layer box in the projects page
(more to come ?)

**Comment by NeusFear** [comment]
There would still be a modal with the UI mockup scribble I sent in discord, just a reorganized one.

**Comment by Wyn-Price** [comment]
What needs to be done with this now?

**Comment by NeusFear** [comment]
I don't think anything. I'll cover the UI polish in my final pass
