### ISSUE TITLE
Cubes seem to become larger when attempting to move rotation point using Gumball

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#112]
- For some reason attempting to move the rotation point of a cube causes it to become slightly larger with no change in the actual values
- Offset and Position gumballs are not afflicted by this bug

https://imgur.com/hhslbzW

**Comment by BrownBoiiWonder** [comment]
the cubes returning to previous size happens when I hit undo

**Comment by NeusFear** [comment]
I don't think it was getting bigger, I think it was moving to the side, but yeah still a bug

**Comment by BrownBoiiWonder** [comment]
it affects any cube with cube grow axial and non-axial
cubes w/o cube grow are unaffected
As Neus pointed out, the cubes do move but there is still some weird increase in height
