### ISSUE TITLE
BlockBench Import textures timeout / not responding

### ISSUE THREAD

**Issue by bradleyq** [Dumb-Code/DumbCode-Studio#140]
https://streamable.com/4c2q2s
Particular model:
![image](https://user-images.githubusercontent.com/2925806/103727471-3059ab80-4f90-11eb-812b-16f676795df5.png)

**Comment by NeusFear** [comment]
Closing as this was done in an unsupported version of the studio. Hopefully, this issue will be fixed in the dev studio we are working on now which is targeted to be the version we release fully.
