### ISSUE TITLE
BlockBench Import UV not scaled to texture size, uses 16 x 16 instead.

### ISSUE THREAD

**Issue by bradleyq** [Dumb-Code/DumbCode-Studio#141]
I had to manually import the texture to get this imported see #140 

![image](https://user-images.githubusercontent.com/2925806/103727471-3059ab80-4f90-11eb-812b-16f676795df5.png)
![image](https://user-images.githubusercontent.com/2925806/103727712-c8f02b80-4f90-11eb-849b-365786ee1676.png)

**Comment by NeusFear** [comment]
Closing as this was done in an unsupported version of the studio. Hopefully, this issue will be fixed in the dev studio we are working on now which is targeted to be the version we release fully.
