### ISSUE TITLE
Sometimes importing tbl and dcm files into Project Page doesn't work

### ISSUE THREAD

**Issue by kashgummaraju** [Dumb-Code/DumbCode-Studio#149]
@GammaHyperion had a similar issue with the mosasaurus dcm file

![image](https://user-images.githubusercontent.com/3739555/105570378-e4339880-5cfd-11eb-9a5a-1f88d8a3f786.png)

Popped up in Console Log when trying & failing to import triceratops tbl file through both drag and drop and hitting "Upload New Model" button

**Comment by BrownBoiiWonder** [comment]
RIP this happened with every tbl and dcm file I tried

**Comment by BrownBoiiWonder** [comment]
Tried hard refreshing and it got resolved??

**Comment by NeusFear** [comment]
@kashgummaraju is this still a problem?
