### ISSUE TITLE
Grounding cube improvements

### ISSUE THREAD

**Issue by NeusFear** [Dumb-Code/DumbCode-Studio#15]
On the texture tab the grounding cube (the lil blue cube under the model) obstructs the bottom of the model keeping you from being able to paint on it. this can be solved by removing it completely on the texture tab or by giving a toggle switch may be under the viewport similar to the model tab.

It would also be nice if it were colored the same as texture maps to kind of give a better indication of what direction it is facing.

On the animation tab it would be helpful to make the cube larder for grounding the animations so there could be some improvements made there too.

**Comment by BrownBoiiWonder** [comment]
Another improvement could be an actual texture for the grounding cube to make it not flat af blue, similar to how Tabula textures the grounding cube depending on the theme and resource pack.

**Comment by NeusFear** [comment]
Not really allowed I don't think since our program is not a mod like Tabula we can't use the pre-distributed textures from Minecraft itself so we'd have to have our own texture not taken from the game to avoid copyright issues with texture redistribution.

**Comment by BrownBoiiWonder** [comment]
Yeah we should use our own texture
