### ISSUE TITLE
A couple of suggestions regarding Project Tab and its workflow

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#159]
Preface: _A lot of this has to do with the Project Page, unfortunately, the more I use the Studio and as non-modelers like @Mazeekeen use it, it's apparent that while the Project Page is great for initially setting stuff up, uploading, pushing/committing using the remote when you're wrapping up, getting all your stuff in/out. Having to navigate to and fro between the other three tabs and Project Page is a hindrance to speed and convenience. Despite original intentions to make each tab "distraction-free" and focused, it has become very much a distraction since there's nothing convenient nor traditional about it._

1. A dropdown menu on the Project Tab that allows you to quickly switch between projects, as opposed to the current system for switching/referencing between two projects
- User has to go to Project Page, click on the other model, go to the model tab, take a peek, go back to the project page, click on the model, and then go back to the model tab. Rinse and Repeat for every time they need to reference a value, cube size, names, etc

2. A set of tabs within the Modeling tab akin to Animator tabs that display up to 5 of the most recently opened models. Not totally necessary but would be nice. In my view as basically the sole "power" user, I want as few clicks as possible, doesn't matter if it's just three or four clicks, it's the distance I gotta travel w/ my mouse(sounds lazy af ik) + going back and forth. This would reduce switching between projects(at least those that fall under recently opened) to two measly quick clicks w/minimal mouse travel)
- I'd suggest moving the command input literally anywhere at the bottom bar, and giving the space to the tabs. It's just too much space for the input and history, and it's a waste tbh for it to take it up like that. 
![image](https://user-images.githubusercontent.com/3739555/106095355-87aeef80-60e8-11eb-91bf-ba04866303a0.png)
- It's even more of a waste of space considering how small the input space itself is:
![image](https://user-images.githubusercontent.com/3739555/106095598-e7a59600-60e8-11eb-951d-20180c2c4c90.png)
- even the input history takes up a mere fraction:
![image](https://user-images.githubusercontent.com/3739555/106095678-073cbe80-60e9-11eb-8055-30bbad3c64bb.png)

3. Ability to upload & download textures within the texture tab, same reason as **#1**, it's too many steps. It's a lot faster and simpler for texture artists to upload and download textures without having to switch between tabs, especially in lieu of a listening feature.

**Comment by NeusFear** [comment]
Feel free to open a new issue if you find issues with the dev site layout but for now since these are based on the layout of the live site I will close this one
