### ISSUE TITLE
Rotation doesn't work in animation (v0.8.10)

### ISSUE THREAD

**Issue by GundunUkan** [Dumb-Code/DumbCode-Studio#165]
Apologies if this is just me being stupid but rotations don't work in the animation tab. The value changes but there is no visual change, even the slider doesn't move and when you click away and then back on the part the value has been reset.

**Comment by GammaHyperion** [comment]
Did you click "New animation", then "New layer", then on the "+" to make a new keyframe? If not, it doesn't work.

**Comment by GundunUkan** [comment]
I did but the "+" on the layer wasn't clickable. I finicked around with it more and apparently the issue was that the interaction box on the "+" and the other layer tools is a bit too small and hard to hit.

**Comment by GammaHyperion** [comment]
Can you make a separate issue for the interaction box around the icon? I'll close this issue now, then.
