### ISSUE TITLE
Padlock and View options 

### ISSUE THREAD

**Issue by JustMrDevilGH** [Dumb-Code/DumbCode-Studio#168]
The Padlock to lock the layers and the View Eye to make visible/invisible some layers in the animations should become blue when its active, this is to make it more visible the option, because its really small and someone could accidentaly turn on one of those options and he will confuse because he can't edit layers becuase he didn't realized that one of those options was activated.

**Comment by NeusFear** [comment]
This has been implemented on the dev site intended for the 1.0 release. This feature won't make it to the current live site, but you can expect it in the future
