### ISSUE TITLE
Rotation values get out of sync between tabs

### ISSUE THREAD

**Issue by parzivail** [Dumb-Code/DumbCode-Studio#169]
1. Open model
2. Go to animation editor
3. Rotate any part
4. Go back to model editor
5. Parts will be rotated but the part angles will be zero, and any attempt to modify the angle results in the part being modified further, as if the rotation set in the animation editor "resets" the zero position
	* Additionally, the undo/redo stack does not contain the rotation, and cannot be undone

**Comment by NeusFear** [comment]
This has been fixed on dev
