### ISSUE TITLE
Rotation gizmo in the animation editor does not accurately reflect the plane on which the part will rotate

### ISSUE THREAD

**Issue by parzivail** [Dumb-Code/DumbCode-Studio#171]
1. Open model
2. Go to animation editor and create a new animation, layer and keyframe
3. Rotate any part multiple times on multiple axes
4. Click the part again and observe the rotation gizmo, and attempt to rotate it again choosing any axis
5. Observe that the gizmo circles do not lie in the planes that the cube will rotate on

**Comment by NeusFear** [comment]
I'm not sure that I understand, because the gumball shouldn't be available on the animator right now, it is meant to be in the future but if I recall this is a not-yet implemented feature. if you have a gif that you could make that would help

**Comment by NeusFear** [comment]
No longer an issue
