### ISSUE TITLE
Box names (v0.8.11)

### ISSUE THREAD

**Issue by GundunUkan** [Dumb-Code/DumbCode-Studio#182]
Models transferred with the latest Tabula format do not retain their box names, instead switching to Box~X

**Comment by Wyn-Price** [comment]
In the studio, boxes have to have unique names. If they don't, they're appended with ~N to make them unique

**Comment by Wyn-Price** [comment]
This is something that could change in the future but is not changing anytime soon

**Comment by GundunUkan** [comment]
They do have unique names pre transfer from tabula, the names just don't preserve ![image](https://user-images.githubusercontent.com/26864687/112726626-13959a00-8f27-11eb-8991-82f2d03f479c.png)

**Comment by Wyn-Price** [comment]
Can you send the .tbl model?

**Comment by GundunUkan** [comment]
[WRDemonicWingwalkerIdle.zip](https://github.com/Dumb-Code/DumbCode-Studio/files/6215990/WRDemonicWingwalkerIdle.zip)

**Comment by Wyn-Price** [comment]
Closed in v0.8.12 ce8471b5ef6f05d92e56ad37d13b5601288f37be
