### ISSUE TITLE
Recent History

### ISSUE THREAD

**Issue by kashgummaraju** [Dumb-Code/DumbCode-Studio#188]
![image](https://user-images.githubusercontent.com/3739555/139602232-c1c1e7a5-b7ae-4e63-9863-a2ba24841805.png)

A history of recent actions that would serve to have players do undo or redo without hitting the buttons or keybinds too many times.

**Comment by NeusFear** [comment]
UI Completeish so re-assigning this to you @Wyn-Price

**Comment by NeusFear** [comment]
Done
