### ISSUE TITLE
Translation, Rotation, Dimension wheel and arrow improvements

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#22]
Right now if you select a particular wheel or arrow for the corresponding axis, your selection is indicated by a grey line and the other arrows/wheels becoming translucent and less bright

It would be better if the selected wheel/arrow instead became brighter and the line appearing to be the same color as the arrow. To further emphasize/indicate your selection, the current solution of having the other axes becoming translucent & less bright should still be kept.

Also as suggested in discord, the grey lines that pop up should be the same color as the corresponding axis.

Another suggestion I voiced earlier was for the translation arrows to match the rotation wheel and dimension arrows in having arrows for both positive and negative directions for each axis as opposed to the current implementation of the arrows going in the positive direction only(in relation to the cube's local rotations & position). Because right now it's super easy for the arrows to be obscured and hidden away by cube(s) sitting directly on top, in front, below, behind, etc of a selected cube.

**Comment by Wyn-Price** [comment]
I can change the colors sure. 
I also plan on making the gumball render on top of everything else, so cubes can't obscure it.
