### ISSUE TITLE
Project Tab Model renaming not working

### ISSUE THREAD

**Issue by kashgummaraju** [Dumb-Code/DumbCode-Studio#225]
![studiotest4](https://user-images.githubusercontent.com/3739555/178840973-6d54c337-0788-4e5c-8865-f4479192d7cc.gif)

**Comment by NeusFear** [comment]
Can't reproduce
How did you make this happen?

**Comment by Wyn-Price** [comment]
This happens when the project is linked to a file. You can now right click to unlink a project from a file

**Comment by NeusFear** [comment]
I have added an Icon to better indicate when a file is linked, and the tooltip gives this information to the user
