### ISSUE TITLE
[Bug]: Autosave data bar indicator does not reset when recovery data deleted

### ISSUE THREAD

**Issue by NeusFear** [Dumb-Code/DumbCode-Studio#237]
### Version

Beta (dev.dumbcode.net)

### What browsers have you tested on?

Firefox

### What operating system are you using?

Windows

### What Studio tabs does this issue concern?

Settings/Configuration

### Reproduction steps

```bash
1. Have some Autosaves
2. Click the delete button
3. Notice the progress bard does not reset immediatley
```

### Describe what you EXPECTED to happen.

```text
The bar would show no gree on it
```

### Describe what happened instead.

```text
The ammount of green stayed the same as before I pressed delete
```

**Comment by Wyn-Price** [comment]
Yeah this isn't really a bug. The calculation for how much space is used isn't exactly 100%, and a small amount of space will always be used. If you artificially change the storage size (not sure how to do it on firefox, but chromium it's Application > Storage), then you'll see the data is reduced on deletion. 

Storage space calculations are done every second, I don't think it's too big of an issue for storage size to be a second late. If wanted i can reduce the interval time to 500ms
