### ISSUE TITLE
Lock and Visibility icons overlapping

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#24]
When the side bar is compacted or when cube names are really long, the Lock and Visibility icons overlap onto the names, causing clutter and just grossness

https://cdn.discordapp.com/attachments/741335776473907320/772536502382624818/unknown.png
https://media.discordapp.net/attachments/741335776473907320/772545055558860800/unknown.png

**Comment by Wyn-Price** [comment]
Should I do a minimum width for the sidebar?

**Comment by NeusFear** [comment]
I think we just need to make those icons a pixel width and make the names adjust with the sidebar. min width could be useful but it should be pretty small if added.

**Comment by Wyn-Price** [comment]
im confused what you mean

**Comment by NeusFear** [comment]
the reason this is an issue is that the eye and lock icons' parent div shrinks so they overlap. those parents just need to have not dynamic widths so they dont ever overlap

**Comment by NeusFear** [comment]
Ohhh wait no we just need to hide the overflow of the text div

**Comment by Wyn-Price** [comment]
That works
