### ISSUE TITLE
The values section of sidebar is not affected by the world/local toggle on bottom bar

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#27]
setting the move values on the arrows to world or local doesn't affect the manual inputs, it's set to local translation, a pain to use when arrows are hidden in other cubes.
[https://cdn.discordapp.com/attachments/741335776473907320/772305774869086258/Studiotest14.gif](url)

**Comment by Wyn-Price** [comment]
This is intended. The local/world only effects the gumball. I don't think having it the other way would make sense, considering where the local/world switch is currently placed.
