### ISSUE TITLE
Cube List doesn't expand when the values part of sidebar is detached

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#28]
[url](https://cdn.discordapp.com/attachments/741335776473907320/772847091642269746/Studiotest16.gif)

**Comment by Wyn-Price** [comment]
Thats because when the sidebar is detatched, the cube list expands the whole screen. For some reason that isn't happening

**Comment by Wyn-Price** [comment]
Probably related to #25
