### ISSUE TITLE
Tabs dont show what program you're currently on.

### ISSUE THREAD

**Issue by NeusFear** [Dumb-Code/DumbCode-Studio#35]
there is no indicator to what studio tab is selected (project, modeler, texturer or animator)

**Comment by Wyn-Price** [comment]
Maybe we could have some text next to the tabs to say the current tab?

**Comment by NeusFear** [comment]
or just change the color when it's selected

**Comment by Wyn-Price** [comment]
Oh I misread the question. I thought you were talking about the name of the current project. They can easily change color
