### ISSUE TITLE
Cube disappearing

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#37]
Had a cube(lowerJawlow2) go missing when I locked it into place so that I could move the parent cube around. Using the translation arrows, I moved the parent cube and the cube(lowerJawlow2) disappeared. The positions had no values and were empty.
![image](https://user-images.githubusercontent.com/3739555/98167351-c8a6b780-1e9d-11eb-9647-145e5ea2a7f1.png)

Console log:
![image](https://user-images.githubusercontent.com/3739555/98167367-cfcdc580-1e9d-11eb-967c-ac608d6a70d3.png)

I tried editing the position values but only a gumball showed up:
![image](https://user-images.githubusercontent.com/3739555/98167413-e3792c00-1e9d-11eb-9cc1-dec32ab973e1.png)

Hitting undo didn't do anything either

**Comment by Wyn-Price** [comment]
What was the dimensions of the cube?
