### ISSUE TITLE
Locking cubes to change offset w/o affecting position

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#38]
Locking cube to change offset w/o affecting position is bugged. The locked cube still moves as if it's unlocked when messing with the offset values

https://cdn.discordapp.com/attachments/741335776473907320/773604932250501160/Studiotest19.gif

**Comment by NeusFear** [comment]
this is meant to be done with the offset move option not with cube locking

**Comment by NeusFear** [comment]
https://i.gyazo.com/393bf0646ae0140a2d8c8ff08f8d5ead.mp4

**Comment by BrownBoiiWonder** [comment]
That's a really imprecise way to do it

**Comment by NeusFear** [comment]
The precision will be fixed once we have https://github.com/Dumb-Code/DumbCode-Studio/issues/13

**Comment by Wyn-Price** [comment]
> The precision will be fixed once we have #13
This isn't true. Offset applies the rotation, so if the cubes rotated then you'd have to move it around in the different axis.

Currently, cube locking doesn't effect offset, only position and rotation.

What you're trying to do isn't really like anything currently implimented
