### ISSUE TITLE
Moving offset using translation arrows is scuffed af

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#39]
Moving the offset pt using translation arrows ie not precise, moves the cube too instead of purely just the offset pt
Locking the cube doesn't do anything at all, the offset point will just look like it's being moved

https://cdn.discordapp.com/attachments/741335776473907320/773658252122128384/Studiotest21.gif

**Comment by Wyn-Price** [comment]
????
In the gif, you're moving the offset. Of course the cube itself will move.  If you want to move the rotation point by itsself, click the rotation point option.

Locking cubes does not effect offset
