### ISSUE TITLE
Add different scroll speeds

### ISSUE THREAD

**Issue by GammaHyperion** [Dumb-Code/DumbCode-Studio#43]
There need to be different scroll speeds in the animator rotations/positions tabs. 
Scrolling on slider: Normally: 0.36
                            When holding Ctrl: 0.04
                            When holding Shift: 3.6

Scrolling on number: Normally: 0.1
                                When holding Ctrl: 0.01
                                When holding Shift: 1.0

Dragging the bar should be a difference of 2.61
Dragging the wheel should be a difference of 1.575

**Comment by Wyn-Price** [comment]
Related #17 

Also where did you get the numbers from?

**Comment by GammaHyperion** [comment]
> 
> 
> Related #17
> 
> Also where did you get the numbers from?

I got them from the number Tabula uses. They're pretty much perfectly usable.

**Comment by GammaHyperion** [comment]
> 
> 
> Related #17
> 
> Also where did you get the numbers from?

Also, the other issue I just posted is a replica of issue 17, sorry didn't see that
