### ISSUE TITLE
Progression point stuff gets hidden when zoomed in

### ISSUE THREAD

**Issue by GammaHyperion** [Dumb-Code/DumbCode-Studio#48]
The inputs (especially on the right side) of the animator is pretty small, would like it to be larger, or have the option to zoom in/enlarge it.

**Comment by NeusFear** [comment]
Have you tried just using your browser zoom? Like holding left control and scrolling

**Comment by GammaHyperion** [comment]
I haven't. Works well, but I can't scroll the tab to go down to the progression point stuff, since that gets hidden on the bottom.

**Comment by NeusFear** [comment]
That can probably be fixed
