### ISSUE TITLE
Suggestion: Auto-centering offset pt

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#49]
A way/feature to center the offset point on each individual axes, not together. Should also calculate and center according to cube grow on specific axis as well.

**Comment by Wyn-Price** [comment]
I'm confused what you mean

**Comment by BrownBoiiWonder** [comment]
A feature to automatically move the offset pt to the center of the x,y,and z axes. If the dimension of the cube is 4 on the x-axis, you'd be able to automatically set the offset on the x-axis to -2 and so on.

**Comment by NeusFear** [comment]
I think a better way to do this would be to allow vertex snapping for the rotation point without moving the cube
