### ISSUE TITLE
Texture map is movable when painting.

### ISSUE THREAD

**Issue by NeusFear** [Dumb-Code/DumbCode-Studio#7]
When using the pain tool on the texturemap window instead of on the model itself the texturemap is moved underneath the cursor still. The ability to drag texturemaps to adjust the offsets should be locked while in "paint mode"

**Comment by Wyn-Price** [comment]
Still the case?

**Comment by NeusFear** [comment]
yes

**Comment by Wyn-Price** [comment]
Left click to paint, right click to move. 
![pZOS2s7CYd](https://user-images.githubusercontent.com/15876682/102516842-3b06dc00-4087-11eb-859d-eb80d5f42466.gif)

**Comment by NeusFear** [comment]
Add a cube to your model and try painting on the texturemap, the uvs are what move not the canvas
