### ISSUE TITLE
Reference Image

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#79]
- Places a 2D plane with an uploaded image centered on the Z axis by default. 
- Plane can be rotated on the X and Y axis as well
- Can also be resized
- Can have its opacity adjusted
- Can be moved up and down on the Y axis

**Comment by Wyn-Price** [comment]
What should the UI/Controls be

**Comment by BrownBoiiWonder** [comment]
Go go @NeusFear rangers

**Comment by NeusFear** [comment]
I'll think about it
