### ISSUE TITLE
Snapping button when pressed has an incomplete white outline that doesn't go away

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#81]
https://imgur.com/a/SNv2ITw

**Comment by Wyn-Price** [comment]
It shouldn't be white in the first place @NeusFear 
The button is for executing commands, not a toggle mode

**Comment by NeusFear** [comment]
this is a bug on chromium browsers :/ css just needs edited to accomodate in the common_commands.html file
basically the --webkit-<blah> stuff
