### ISSUE TITLE
Reference Image UI needs tweaks

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#92]
Seems as though the entire UI functions as the Upload Image button as opposed to just the icon
![image](https://user-images.githubusercontent.com/3739555/103037730-670bdc80-4521-11eb-9551-5a1d11c68618.png)

**Comment by BrownBoiiWonder** [comment]
Correction:
Only the icon acts as the button but the tooltip and mouse cursor seem to treat the entire length of the UI as a button

**Comment by BrownBoiiWonder** [comment]
https://imgur.com/JKKxuse

This is just confusing

What is that icon/button next to the image name

There should not be a horizontal scroll bar, It would be better if the UI was made to be longer and the characters to have a display limit

**Comment by Wyn-Price** [comment]
That is the opacity slider. For some reason your modal is really small
