### ISSUE TITLE
Reference Image is blocking cube selection in the viewer

### ISSUE THREAD

**Issue by kashgummaraju** [Dumb-Code/DumbCode-Studio#93]
Once imported and moved to align with the model/cubes, the reference image effectively prevents the user from selecting the cubes within the bounds of the image. 

https://imgur.com/a/zVpH2wK

![image](https://user-images.githubusercontent.com/3739555/103042573-ebb12780-452e-11eb-85e3-f72e608f7bb8.png)

**Comment by BrownBoiiWonder** [comment]
Update: If the user is looking at the model and image mostly on the X-axis, the bug in question occurs. Looking it at on the Z and Y axis does not affect cube selection

**Comment by BrownBoiiWonder** [comment]
https://media.discordapp.net/attachments/741335776473907320/791439756185436160/unknown.png?width=1183&height=613
https://media.discordapp.net/attachments/741335776473907320/791439876796186624/unknown.png?width=476&height=614

**Comment by BrownBoiiWonder** [comment]
Another update:
So the issue affects the axis perpendicular to the axis that the image is aligned to. If it's aligned to the X axis, then it will block selection on the Z axis and vice versa.

If however the image is rotated to face the Y axis, then only the Y-axis is affected:
![image](https://user-images.githubusercontent.com/3739555/103042982-37b09c00-4530-11eb-881e-540beab6b46c.png)

![image](https://user-images.githubusercontent.com/3739555/103042995-4303c780-4530-11eb-81b2-0a6c8895c8d7.png)

**Comment by BrownBoiiWonder** [comment]
https://imgur.com/Ni5aJ1h

**Comment by NeusFear** [comment]
Closing with an enhancement issue #198
