### ISSUE TITLE
Unparenting and parenting cubes should not affect the position

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#96]
Currently parenting a cube or unparenting it will cause it to be moved. 

Like our previous implementation in tabula, this should not occur. A cube should remain where it is when parented or unparented.

**Comment by BrownBoiiWonder** [comment]
Expanding on this issue, parenting and unparenting also causes the rotation of the cube to be altered to match the "parent"

SailMembrane1 not parented to any cube: XYZ rotations are 0 degrees
![image](https://user-images.githubusercontent.com/3739555/103143326-d5d76a00-46c8-11eb-9241-83a3985e066d.png)

SailMembrane1 parented to shoulder cube: rotations are 0 degrees but cube is clearly same rotation as parent Shoulder cube
![image](https://user-images.githubusercontent.com/3739555/103143332-f56e9280-46c8-11eb-93e0-2fcf8a2e7fad.png)

When SailMembrane1 is unparented, it goes back to "0" degrees in relation to the ground cube or whatever

**Comment by Wyn-Price** [comment]
bruh

**Comment by Wyn-Price** [comment]
You know the cube values on the right show the cubes rotation. If the cube is re-parented and not kept in the same place (which it should be doing) then obviously the numbers wont change

**Comment by BrownBoiiWonder** [comment]
Pre-parenting
https://cdn.discordapp.com/attachments/741335776473907320/792189969682661406/unknown.png

Post-parenting
https://cdn.discordapp.com/attachments/741335776473907320/792190054017138752/unknown.png

Essentially as Neus put it "it should be changing the rotation values to keep its world rotation but it’s not"

**Comment by BrownBoiiWonder** [comment]
![image](https://user-images.githubusercontent.com/3739555/103143825-53a07300-46d3-11eb-90ff-667cd75cc106.png)
Console log also present in screenshot
Same issue with different models
- Replicated it on 2 different models both dcm and tbl: Rex(dcm) and Triceratops(tbl)

Screenshotting tool keybind used is alt+q not ctrl+q
![image](https://user-images.githubusercontent.com/3739555/103143834-82b6e480-46d3-11eb-8fef-60614d0c85ec.png)
